\c portfolio_dev;

INSERT INTO projects (name, technology, module, description, revisit, repo_link) VALUES 
('Weather App', 'Postman', 2, 'Small Weather App using an external API', true, 'https://github.com/SangunPark96/9-3-weather-app-project'),
('Youtube Clone', 'React', 3, 'A static youtube clone using googles API', true, 'https://github.com/joshuanelsondev/YouTube-project'),
('Budget App', 'PostGres', 4, 'Budget App utilizing SQL and PostGres', false, 'https://github.com/SangunPark96/Budget-App-Frontend');

INSERT INTO interests (name, media_type, genre, still_enjoy, img_link, summary) VALUES
('Red Dead Redemption 2', 'video game', 'western', true, 'https://image.api.playstation.com/cdn/UP1004/CUSA03041_00/Hpl5MtwQgOVF9vJqlfui6SDB5Jl4oBSq.png', 'After a robbery goes badly wrong in the western town of Blackwater, Arthur Morgan and the Van der Linde gang are forced to flee. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive.'),
('Civilization 6', 'video game', 'historical', true, 'https://downloads.2kgames.com/vnbh3gjdfkeit4utey6pdmds12/civ/img/CivilizationVI_keyart_horizontal_thm.jpg', 'Civilization VI is a turn-based strategy video game in which one or more players compete alongside computer-controlled AI opponents to grow their individual civilization from a small tribe to control of the entire planet across several periods of development.'),
('League of Legends', 'video game', 'fantasy', false, 'https://editors.dexerto.com/wp-content/uploads/2022/09/24/tyler1-league-of-legends-rage.jpg', 'League of Legends is a multiplayer online battle arena game in which the player controls a character with a set of unique abilities from an isometric perspective. As of 2023, there are over 160 champions available to play.'),
('The Dark Forest by Liu Cixin', 'book', 'sci-fi', true, 'https://static.tvtropes.org/pmwiki/pub/images/tdf_9.png', 'This is a story of existential crisis: Desperate to escape their inhospitable planet, which is doomed to be consumed by one or more of the three suns in its solar system, the Trisolarans have dispatched a thousand warships to wipe out humankind and claim Earth as their new home.'),
('Pop Team Epic', 'anime', 'comedy', true, 'https://upload.wikimedia.org/wikipedia/en/8/87/Pop_Team_Epic_volume_1_cover.jpg', 'Popuko and Pipimi are a pair of foul mouthed girls ready to take on every pop culture reference ever made. Pop Team Epic follows the pair through a series of surreal skits and short stories full of internet, movie, video game, and self-referential based comedy.');